[package]
name = "dat4-view"
version = "0.1.0"
authors = ["Smail <SmailBarkouch1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

plotters = "0.2"
minigrep = "0.1.0"
